# fly.toml file generated for puhluettelopart3 on 2023-02-23T22:38:23+02:00
# Modified to include CI/CD process in Part 11

app = "puhluettelopart3"

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
